
import { Word } from './types';

export const CATEGORIES_DATA: Record<'words' | 'phrases', Record<string, Word[]>> = {
    words: {
        animals: [
            { id: 'a1', pl: 'Pies', en: 'Dog', emoji: '🐶' },
            { id: 'a2', pl: 'Kot', en: 'Cat', emoji: '🐱' },
            { id: 'a3', pl: 'Słoń', en: 'Elephant', emoji: '🐘' },
            { id: 'a4', pl: 'Lew', en: 'Lion', emoji: '🦁' },
            { id: 'a5', pl: 'Tygrys', en: 'Tiger', emoji: '🐯' },
            { id: 'a6', pl: 'Ptak', en: 'Bird', emoji: '🐦' },
            { id: 'a7', pl: 'Ryba', en: 'Fish', emoji: '🐟' },
            { id: 'a8', pl: 'Królik', en: 'Rabbit', emoji: '🐰' },
            { id: 'a9', pl: 'Koń', en: 'Horse', emoji: '🐴' },
            { id: 'a10', pl: 'Krowa', en: 'Cow', emoji: '🐮' },
            { id: 'a11', pl: 'Świnia', en: 'Pig', emoji: '🐷' },
            { id: 'a12', pl: 'Owca', en: 'Sheep', emoji: '🐑' },
            { id: 'a13', pl: 'Małpa', en: 'Monkey', emoji: '🐒' },
            { id: 'a14', pl: 'Niedźwiedź', en: 'Bear', emoji: '🐻' },
            { id: 'a15', pl: 'Wilk', en: 'Wolf', emoji: '🐺' },
            { id: 'a16', pl: 'Lis', en: 'Fox', emoji: '🦊' },
            { id: 'a17', pl: 'Żyrafa', en: 'Giraffe', emoji: '🦒' },
            { id: 'a18', pl: 'Zebra', en: 'Zebra', emoji: '🦓' },
            { id: 'a19', pl: 'Wąż', en: 'Snake', emoji: '🐍' },
            { id: 'a20', pl: 'Mysz', en: 'Mouse', emoji: '🐭' }
        ],
        rooms: [
            { id: 'r1', pl: 'Kuchnia', en: 'Kitchen', emoji: '🍳' },
            { id: 'r2', pl: 'Salon', en: 'Living room', emoji: '🛋️' },
            { id: 'r3', pl: 'Łazienka', en: 'Bathroom', emoji: '🚿' },
            { id: 'r4', pl: 'Sypialnia', en: 'Bedroom', emoji: '🛏️' },
            { id: 'r5', pl: 'Garaż', en: 'Garage', emoji: '🚗' },
            { id: 'r6', pl: 'Piwnica', en: 'Basement', emoji: '📦' },
            { id: 'r7', pl: 'Strych', en: 'Attic', emoji: '🕸️' },
            { id: 'r8', pl: 'Przedpokój', en: 'Hallway', emoji: '🧥' },
            { id: 'r9', pl: 'Jadalnia', en: 'Dining room', emoji: '🍽️' },
            { id: 'r10', pl: 'Gabinet', en: 'Office', emoji: '🖥️' },
            { id: 'r11', pl: 'Balkon', en: 'Balcony', emoji: '🪴' },
            { id: 'r12', pl: 'Taras', en: 'Terrace', emoji: '☀️' },
            { id: 'r13', pl: 'Ogród', en: 'Garden', emoji: '🌻' },
            { id: 'r14', pl: 'Schody', en: 'Stairs', emoji: '🪜' },
            { id: 'r15', pl: 'Winda', en: 'Elevator', emoji: '🛗' },
            { id: 'r16', pl: 'Dach', en: 'Roof', emoji: '🏠' },
            { id: 'r17', pl: 'Podłoga', en: 'Floor', emoji: '🧹' },
            { id: 'r18', pl: 'Sufit', en: 'Ceiling', emoji: '💡' },
            { id: 'r19', pl: 'Ściana', en: 'Wall', emoji: '🖼️' },
            { id: 'r20', pl: 'Okno', en: 'Window', emoji: '🪟' }
        ],
        food: [
            { id: 'f1', pl: 'Jabłko', en: 'Apple', emoji: '🍎' },
            { id: 'f2', pl: 'Chleb', en: 'Bread', emoji: '🍞' },
            { id: 'f3', pl: 'Masło', en: 'Butter', emoji: '🧈' },
            { id: 'f4', pl: 'Ser', en: 'Cheese', emoji: '🧀' },
            { id: 'f5', pl: 'Jajko', en: 'Egg', emoji: '🥚' },
            { id: 'f6', pl: 'Mleko', en: 'Milk', emoji: '🥛' },
            { id: 'f7', pl: 'Woda', en: 'Water', emoji: '💧' },
            { id: 'f8', pl: 'Kawa', en: 'Coffee', emoji: '☕' },
            { id: 'f9', pl: 'Herbata', en: 'Tea', emoji: '🍵' },
            { id: 'f10', pl: 'Mięso', en: 'Meat', emoji: '🥩' },
            { id: 'f11', pl: 'Ryż', en: 'Rice', emoji: '🍚' },
            { id: 'f12', pl: 'Makaron', en: 'Pasta', emoji: '🍝' },
            { id: 'f13', pl: 'Zupa', en: 'Soup', emoji: '🍜' },
            { id: 'f14', pl: 'Sałatka', en: 'Salad', emoji: '🥗' },
            { id: 'f15', pl: 'Ciasto', en: 'Cake', emoji: '🍰' },
            { id: 'f16', pl: 'Lody', en: 'Ice cream', emoji: '🍦' },
            { id: 'f17', pl: 'Sok', en: 'Juice', emoji: '🧃' },
            { id: 'f18', pl: 'Owoce', en: 'Fruit', emoji: '🍓' },
            { id: 'f19', pl: 'Warzywa', en: 'Vegetables', emoji: '🥦' },
            { id: 'f20', pl: 'Cukier', en: 'Sugar', emoji: '🍬' }
        ],
        electronics: [
            { id: 'e1', pl: 'Komputer', en: 'Computer', emoji: '💻' },
            { id: 'e2', pl: 'Myszka', en: 'Mouse', emoji: '🖱️' },
            { id: 'e3', pl: 'Klawiatura', en: 'Keyboard', emoji: '⌨️' },
            { id: 'e4', pl: 'Kabel', en: 'Cable', emoji: '🔌' },
            { id: 'e5', pl: 'Bateria', en: 'Battery', emoji: '🔋' },
            { id: 'e6', pl: 'Ekran', en: 'Screen', emoji: '📺' },
            { id: 'e7', pl: 'Telefon', en: 'Phone', emoji: '📱' },
            { id: 'e8', pl: 'Słuchawki', en: 'Headphones', emoji: '🎧' },
            { id: 'e9', pl: 'Ładowarka', en: 'Charger', emoji: '⚡' },
            { id: 'e10', pl: 'Laptop', en: 'Laptop', emoji: '💻' },
            { id: 'e11', pl: 'Tablet', en: 'Tablet', emoji: '📟' },
            { id: 'e12', pl: 'Głośnik', en: 'Speaker', emoji: '🔊' },
            { id: 'e13', pl: 'Kamera', en: 'Camera', emoji: '📷' },
            { id: 'e14', pl: 'Pilot', en: 'Remote control', emoji: '🎮' }
        ],
        clothes: [
            { id: 'c1', pl: 'Koszula', en: 'Shirt', emoji: '👕' },
            { id: 'c2', pl: 'Spodnie', en: 'Pants', emoji: '👖' },
            { id: 'c3', pl: 'Buty', en: 'Shoes', emoji: '👟' },
            { id: 'c4', pl: 'Czapka', en: 'Hat', emoji: '🧢' },
            { id: 'c5', pl: 'Sukienka', en: 'Dress', emoji: '👗' },
            { id: 'c6', pl: 'Kurtka', en: 'Jacket', emoji: '🧥' },
            { id: 'c7', pl: 'Skarpetki', en: 'Socks', emoji: '🧦' },
            { id: 'c8', pl: 'Spódnica', en: 'Skirt', emoji: '👗' },
            { id: 'c9', pl: 'Płaszcz', en: 'Coat', emoji: '🧥' },
            { id: 'c10', pl: 'Rękawiczki', en: 'Gloves', emoji: '🧤' },
            { id: 'c11', pl: 'Pasek', en: 'Belt', emoji: '🎫' },
            { id: 'c12', pl: 'Krawat', en: 'Tie', emoji: '👔' },
            { id: 'c13', pl: 'Sweter', en: 'Sweater', emoji: '🧶' },
            { id: 'c14', pl: 'Szalik', en: 'Scarf', emoji: '🧣' },
            { id: 'c15', pl: 'Krótkie spodenki', en: 'Shorts', emoji: '🩳' },
            { id: 'c16', pl: 'Piżama', en: 'Pajamas', emoji: '🛌' },
            { id: 'c17', pl: 'Kozaki', en: 'Boots', emoji: '👢' },
            { id: 'c18', pl: 'Okulary przeciwsłoneczne', en: 'Sunglasses', emoji: '🕶️' }
        ],
        nature: [
            { id: 'n1', pl: 'Drzewo', en: 'Tree', emoji: '🌳' },
            { id: 'n2', pl: 'Kwiat', en: 'Flower', emoji: '🌸' },
            { id: 'n3', pl: 'Słońce', en: 'Sun', emoji: '☀️' },
            { id: 'n4', pl: 'Księżyc', en: 'Moon', emoji: '🌙' },
            { id: 'n5', pl: 'Gwiazda', en: 'Star', emoji: '⭐' },
            { id: 'n6', pl: 'Rzeka', en: 'River', emoji: '🌊' },
            { id: 'n7', pl: 'Góra', en: 'Mountain', emoji: '⛰️' },
            { id: 'n8', pl: 'Morze', en: 'Sea', emoji: '🌊' },
            { id: 'n9', pl: 'Trawa', en: 'Grass', emoji: '🌱' },
            { id: 'n10', pl: 'Las', en: 'Forest', emoji: '🌲' },
            { id: 'n11', pl: 'Niebo', en: 'Sky', emoji: '☁️' },
            { id: 'n12', pl: 'Chmura', en: 'Cloud', emoji: '☁️' },
            { id: 'n13', pl: 'Deszcz', en: 'Rain', emoji: '🌧️' },
            { id: 'n14', pl: 'Śnieg', en: 'Snow', emoji: '❄️' },
            { id: 'n15', pl: 'Wiatr', en: 'Wind', emoji: '🌬️' },
            { id: 'n16', pl: 'Wyspa', en: 'Island', emoji: '🏝️' },
            { id: 'n17', pl: 'Jezioro', en: 'Lake', emoji: '🏞️' },
            { id: 'n18', pl: 'Tęcza', en: 'Rainbow', emoji: '🌈' }
        ],
        school: [
            { id: 's1', pl: 'Długopis', en: 'Pen', emoji: '🖋️' },
            { id: 's2', pl: 'Ołówek', en: 'Pencil', emoji: '✏️' },
            { id: 's3', pl: 'Zeszyt', en: 'Notebook', emoji: '📒' },
            { id: 's4', pl: 'Książka', en: 'Book', emoji: '📖' },
            { id: 's5', pl: 'Plecak', en: 'Backpack', emoji: '🎒' },
            { id: 's6', pl: 'Biurko', en: 'Desk', emoji: '🏫' },
            { id: 's7', pl: 'Krzesło', en: 'Chair', emoji: '🪑' },
            { id: 's8', pl: 'Linijka', en: 'Ruler', emoji: '📏' },
            { id: 's9', pl: 'Gumka', en: 'Eraser', emoji: '🧼' },
            { id: 's10', pl: 'Tablica', en: 'Blackboard', emoji: '👩‍🏫' },
            { id: 's11', pl: 'Temperówka', en: 'Sharpener', emoji: '🔪' },
            { id: 's12', pl: 'Nożyczki', en: 'Scissors', emoji: '✂️' },
            { id: 's13', pl: 'Klej', en: 'Glue', emoji: '🧴' },
            { id: 's14', pl: 'Mapa', en: 'Map', emoji: '🗺️' },
            { id: 's15', pl: 'Kalkulator', en: 'Calculator', emoji: '🔢' },
            { id: 's16', pl: 'Słownik', en: 'Dictionary', emoji: '📚' },
            { id: 's17', pl: 'Farby', en: 'Paints', emoji: '🎨' },
            { id: 's18', pl: 'Pędzel', en: 'Brush', emoji: '🖌️' }
        ]
    },
    phrases: {
        travel_survival: [
            { id: 'ts1', pl: 'Gdzie jest najbliższa stacja?', en: 'Where is the nearest station?' },
            { id: 'ts2', pl: 'Chciałbym kupić bilet do Londynu.', en: 'I would like to buy a ticket to London.' },
            { id: 'ts3', pl: 'Czy to miejsce jest zajęte?', en: 'Is this seat taken?' },
            { id: 'ts4', pl: 'Czy mogę prosić o menu?', en: 'Can I have the menu, please?' },
            { id: 'ts5', pl: 'Mam alergię na orzechy.', en: 'I am allergic to nuts.' },
            { id: 'ts6', pl: 'Ile to kosztuje?', en: 'How much does this cost?' },
            { id: 'ts7', pl: 'Czy mogę zapłacić kartą?', en: 'Can I pay by card?' },
            { id: 'ts8', pl: 'Stolik dla dwóch osób, poproszę.', en: 'A table for two, please.' },
            { id: 'ts9', pl: 'Reszty nie trzeba.', en: 'Keep the change.' },
            { id: 'ts10', pl: 'Gdzie jest łazienka?', en: 'Where is the bathroom?' },
            { id: 'ts11', pl: 'Mam rezerwację.', en: 'I have a reservation.' },
            { id: 'ts12', pl: 'Czy może mi pan pomóc?', en: 'Can you help me?' },
            { id: 'ts13', pl: 'Zgubiłem się.', en: 'I am lost.' },
            { id: 'ts14', pl: 'Jedną wodę, poproszę.', en: 'One water, please.' },
            { id: 'ts15', pl: 'O której jest następny lot?', en: 'What time is the next flight?' }
        ],
        personality: [
            { id: 'pe1', pl: 'Ona jest bardzo ambitna.', en: 'She is very ambitious.' },
            { id: 'pe2', pl: 'On ma świetne pocie poczucie humoru.', en: 'He has a great sense of humor.' },
            { id: 'pe3', pl: 'Jestem dość nieśmiały.', en: 'I am quite shy.' },
            { id: 'pe4', pl: 'Mój brat jest niezawodny.', en: 'My brother is reliable.' },
            { id: 'pe5', pl: 'Przestań być taki uparty!', en: 'Stop being so stubborn!' },
            { id: 'pe6', pl: 'Ona jest osobą towarzyską.', en: 'She is an outgoing person.' },
            { id: 'pe7', pl: 'On jest znany z uczciwości.', en: 'He is known for his honesty.' },
            { id: 'pe8', pl: 'Nie bądź takim egoistą.', en: 'Don\'t be so selfish.' },
            { id: 'pe9', pl: 'Ona jest bardzo kreatywna.', en: 'She is very creative.' },
            { id: 'pe10', pl: 'Mój przyjaciel jest lojalny.', en: 'My friend is loyal.' },
            { id: 'pe11', pl: 'On wydaje się pewny siebie.', en: 'He seems confident.' },
            { id: 'pe12', pl: 'Podziwiam twoją cierpliwość.', en: 'I admire your patience.' },
            { id: 'pe13', pl: 'Ona jest ostatnio kapryśna.', en: 'She is moody lately.' },
            { id: 'pe14', pl: 'On jest bardzo hojny.', en: 'He is very generous.' },
            { id: 'pe15', pl: 'Przestań być taki wrażliwy.', en: 'Stop being so sensitive.' }
        ],
        cinema_culture: [
            { id: 'cc1', pl: 'Fabuła była wciągająca.', en: 'The plot was engaging.' },
            { id: 'cc2', pl: 'Efekty specjalne były niesamowite.', en: 'The special effects were amazing.' },
            { id: 'cc3', pl: 'Nie podobało mi się zakończenie.', en: 'I didn\'t like the ending.' },
            { id: 'cc4', pl: 'Główny aktor zagrał genialnie.', en: 'The lead actor played brilliantly.' },
            { id: 'cc5', pl: 'To jest oparte na faktach.', en: 'It is based on a true story.' },
            { id: 'cc6', pl: 'Zdjęcia były piękne.', en: 'The cinematography was beautiful.' },
            { id: 'cc7', pl: 'Bardzo polecam ten serial.', en: 'I highly recommend this series.' },
            { id: 'cc8', pl: 'Muzyka jest niesamowita.', en: 'The soundtrack is amazing.' },
            { id: 'cc9', pl: 'To była strata czasu.', en: 'It was a waste of time.' },
            { id: 'cc10', pl: 'Był wielki zwrot akcji.', en: 'There was a big plot twist.' },
            { id: 'cc11', pl: 'Ten film to arcydzieło.', en: 'This movie is a masterpiece.' },
            { id: 'cc12', pl: 'Wolę komedie od horrorów.', en: 'I prefer comedies over horrors.' },
            { id: 'cc13', pl: 'Postacie były dobrze napisane.', en: 'The characters were well written.' },
            { id: 'cc14', pl: 'To stało się hitem w sieci.', en: 'It went viral on the web.' },
            { id: 'cc15', pl: 'On jest fanem science fiction.', en: 'He is a science fiction fan.' }
        ],
        business_office: [
            { id: 'bo1', pl: 'Prześlij mi to mailem.', en: 'Send it to me via email.' },
            { id: 'bo2', pl: 'Mamy dzisiaj spotkanie.', en: 'We have a meeting today.' },
            { id: 'bo3', pl: 'Jaki jest termin oddania?', en: 'What is the deadline?' },
            { id: 'bo4', pl: 'Pracuję nad tym projektem.', en: 'I am working on this project.' },
            { id: 'bo5', pl: 'Czy możemy to omówić?', en: 'Can we discuss this?' },
            { id: 'bo6', pl: 'Zróbmy burzę mózgów.', en: 'Let\'s have a brainstorm.' },
            { id: 'bo7', pl: 'Jestem na urlopie.', en: 'I am on holiday.' },
            { id: 'bo8', pl: 'Potrzebuję twojego podpisu.', en: 'I need your signature.' },
            { id: 'bo9', pl: 'To jest priorytet.', en: 'This is a priority.' },
            { id: 'bo10', pl: 'Dziękuję za współpracę.', en: 'Thank you for your cooperation.' },
            { id: 'bo11', pl: 'Zajmę się tym.', en: 'I will handle this.' },
            { id: 'bo12', pl: 'Mamy przerwę na kawę.', en: 'We have a coffee break.' },
            { id: 'bo13', pl: 'Drukarka nie działa.', en: 'The printer is not working.' },
            { id: 'bo14', pl: 'Zadzwoń do mnie później.', en: 'Call me later.' },
            { id: 'bo15', pl: 'Sprawdź kalendarz.', en: 'Check the calendar.' }
        ]
    }
};

export const TOTAL_QUESTIONS = 14;
